### PG
FROM postgres:15-alpine

RUN apk add --no-cache gettext

# Copy the .env file, the template SQL file, and the script to the container
COPY .env .
COPY env_template_db_init.sql .
COPY env_template_init.sh .

# Make the script executable
RUN chmod +x env_template_init.sh

# Run the script to generate the output.sql file
RUN /bin/sh ./env_template_init.sh

# Optional: Copy the output.sql to the desired location
RUN mv db_init.sql /docker-entrypoint-initdb.d/
